/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthedUserRouteImport } from './routes/_authed/_user'
import { Route as AuthedUserVerifyEmailSuccessRouteImport } from './routes/_authed/_user/verify-email-success'
import { Route as AuthedUserProfileRouteImport } from './routes/_authed/_user/profile'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedUserRoute = AuthedUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserVerifyEmailSuccessRoute =
  AuthedUserVerifyEmailSuccessRouteImport.update({
    id: '/verify-email-success',
    path: '/verify-email-success',
    getParentRoute: () => AuthedUserRoute,
  } as any)
const AuthedUserProfileRoute = AuthedUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedUserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof PublicAboutRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PublicIndexRoute
  '/profile': typeof AuthedUserProfileRoute
  '/verify-email-success': typeof AuthedUserVerifyEmailSuccessRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PublicIndexRoute
  '/profile': typeof AuthedUserProfileRoute
  '/verify-email-success': typeof AuthedUserVerifyEmailSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/_user': typeof AuthedUserRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_authed/_user/profile': typeof AuthedUserProfileRoute
  '/_authed/_user/verify-email-success': typeof AuthedUserVerifyEmailSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/register'
    | '/'
    | '/profile'
    | '/verify-email-success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/register'
    | '/'
    | '/profile'
    | '/verify-email-success'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/_user'
    | '/_public/about'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_authed/_user/profile'
    | '/_authed/_user/verify-email-success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/_user': {
      id: '/_authed/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedUserRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_user/verify-email-success': {
      id: '/_authed/_user/verify-email-success'
      path: '/verify-email-success'
      fullPath: '/verify-email-success'
      preLoaderRoute: typeof AuthedUserVerifyEmailSuccessRouteImport
      parentRoute: typeof AuthedUserRoute
    }
    '/_authed/_user/profile': {
      id: '/_authed/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedUserProfileRouteImport
      parentRoute: typeof AuthedUserRoute
    }
  }
}

interface AuthedUserRouteChildren {
  AuthedUserProfileRoute: typeof AuthedUserProfileRoute
  AuthedUserVerifyEmailSuccessRoute: typeof AuthedUserVerifyEmailSuccessRoute
}

const AuthedUserRouteChildren: AuthedUserRouteChildren = {
  AuthedUserProfileRoute: AuthedUserProfileRoute,
  AuthedUserVerifyEmailSuccessRoute: AuthedUserVerifyEmailSuccessRoute,
}

const AuthedUserRouteWithChildren = AuthedUserRoute._addFileChildren(
  AuthedUserRouteChildren,
)

interface AuthedRouteChildren {
  AuthedUserRoute: typeof AuthedUserRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedUserRoute: AuthedUserRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
