services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

    restart: "unless-stopped"
  frontend:
    container_name: frontend
    build:
      context: ./apps/frontend
    volumes:
      - ./apps/frontend/src:/usr/src/app/src
      - ./apps/frontend/public:/usr/src/app/public

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    # ports:
    #   - "3003:8080"
    volumes:
      - ./apps/backend:/app
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "p@ssw0rd"
      POSTGRES_DB: "labotron_stack"
    restart: always
  adminer:
    image: adminer
    restart: always
    # ports:
    #   - "8080:8080"
