[carbin]
model = './carbin/authz_model.conf'

[cors]
allow_credentials = false
allow_headers = []
allow_methods = []
allow_origin = ['*']
expose_headers = []
max_age = ''

[db]
dsn = 'host=postgres user=username password=p@ssw0rd dbname=labotron_stack port=5432 sslmode=disable TimeZone=Asia/Bangkok'

[jwt]
refresh_secret = 'super_refresh@secret'
secret = 'super@secret'

[mail]
host = 'mail.labotron.co.th'
password = 'itlbm3624567'
port = 587
username = 'matee@labotron.co.th'

[pprof]
enable = false

[server]
host = ''
host_name = ''
port = '3000'
